version: '3.8'

services:
  mpi-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mpi-master
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      sleep 5 &&
      mpirun --allow-run-as-root -n 4 ./mpi_filterer damma.pgm damma_mpi_blur.pgm --f blur
      "
    networks:
      - mpi-network

  mpi-worker-1:
    image: mpi-master   # Usa la imagen ya construida, no recompila
    container_name: mpi-worker-1
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    networks:
      - mpi-network

  mpi-worker-2:
    image: mpi-master
    container_name: mpi-worker-2
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    networks:
      - mpi-network

  mpi-worker-3:
    image: mpi-master
    container_name: mpi-worker-3
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    networks:
      - mpi-network

networks:
  mpi-network:
    driver: bridge
